Just added a few more lines to 'newfile' to give Tori something to pull.
ToriHoush/vision pull request #3
Opened 2016-09-30 18:13 UTC by MichaelJCaruso

I just made a small change to 'newfile' in the 'master' branch of the vision repo.  This should be something simple you can pull.  More to come - see the next pull request I make.

2016-09-30 18:24 UTC, johnmuth81 commented
Hi Michael. I'm John.
Let's see what happens when I make a comment to your pull request.
Here it goes...

2016-09-30 18:27 UTC, johnmuth81 requested changes
Test a negative review comment:

Our coding standards require '==' at the end of an update header ;)

2016-09-30 18:27 UTC, johnmuth81 approved these changes

2016-09-30 18:28 UTC, johnmuth81 commented
Hmm, no comments when I changed my mind to approve

2016-10-01 00:39 UTC, ToriHoush approved these changes

2016-10-01 00:39 UTC, merged